### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Feng-Shiyan** [FrogGuaGuaGua/HighSchoolMathematics#2]
我怎才能解决这些问题？
![Latex](https://github.com/FrogGuaGuaGua/HighSchoolMathematics/assets/108137296/67de97d6-804f-49c9-97b4-16af31b489d2)

**Comment by FrogGuaGuaGua** [comment]
工程师视角下的高中数学-main.tex的第50~51行，我使用了另外的开源字体，但你的电脑上没有这些字体文件，所以报错，直接把这两行注释掉就可以了。我把这个更改merge到main分支里去。
`50    \setCJKmainfont[BoldFont=OPPOSans-B]{SourceHanSerifCN-Regular}
 51    \newCJKfontfamily\KaiTifont{gkai00mp.ttf}`
